---
title: "PS3_MiniProjectMilestone"
format: pdf
---

# Brief Summary

-   Data: newly constructed spatially disaggregated data for London from 1801 to 1921 (micro level data)

-   Main findings:

    -   Invention of the steam railway led to the first large-scale separation of workplace and residence

    -   A class of quantitative urban models is remarkably successful in explaining this

    -   Structurally estimated one model in this type and performed counterfactual analysis

# Replication Target

-   I will focus mainly on reduced-from estimations used in this paper.

    -   Specifically, event-study evidence connecting the decline in population in central areas and the rise in population in outlying areas to the arrival of the railway.

# Original Replication File

-   Data is available for downloading at <https://dataverse.harvard.edu/dataset.xhtml;jsessionid=9dae0e64ad569bdb058fcb0e0e05?persistentId=doi%3A10.7910%2FDVN%2FZCQIMI&version=&q=&fileTypeGroupFacet=%22Document%22&fileAccess=>

-   Relevant processing file: `stata/code/3-reduced-form-regs/StationAccess.do`

-   Relevant datasets:

    -   `data/parish-data.dta`

    -   `data/ttranshat_parish_clean.dta`

    -   `data/ttranscity_parish_clean.dta`

# Draft of Summary Statistics Table

-   This is a panel dataset containing many years, so a table may not be appropriate. I may use figures instead.

-   Specifically, I will try to plot the following variables against time:

    -   number of underground stations

    -   number of overground stations

    -   log parish population
